namespace Domain
{
	public enum GameModes
	{
		SINGLEPLAYER = 1,
		MULTIPLAYER = 1 << 1,
		ZOMBIES = 1 << 3,
		COOP = 1 << 2,
		SINGLE_AND_MULTIPLAYER = SINGLEPLAYER | MULTIPLAYER,
        SINGLE_AND_COOP = SINGLEPLAYER | COOP,
		ZOMBIES_SINGLE_AND_MULTIPLAYER = ZOMBIES | MULTIPLAYER | SINGLEPLAYER
	}
}